name: Build and Test docs
on:
  pull_request:
    types: [submitted]
  # run the workflow if changes pushed to main or release branches
  push:
    branches: '**'
    paths: '**'

# installs dependencies, build the docs and push it to `gh-pages`
jobs:
  docs-test:
    runs-on: [ aia-devops ]
    container:
      image: amr-registry.caas.intel.com/aiops/tlt-dev
      env:
        http_proxy: ${{ secrets.HTTP_PROXY }}
        https_proxy: ${{ secrets.HTTPS_PROXY }}
        no_proxy: ${{ secrets.NO_PROXY }}
      credentials:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}
      volumes:
        - /tf_dataset/dataset/transfer_learning:/tmp/data
    steps:
    - uses: actions/checkout@v3
    - name: Install virtualenv
      run: pip install virtualenv
    - name: Install explainer dependency
      run: cd explainer && make explainer
    - name: Install docs dependencies
      run: cd docs && make install
    # make documentation
    - name: Make documentation
      run: |
        cd explainer && make docs
